### ISSUE TITLE
Project setup - Browser

### ISSUE THREAD

**Issue by mangowi** [dongido001/vue-viaudio#1]
Hi! @dongido001 
Can you provide the docs on how to set-up the project on the Browser?

Thank you in advance.

**Comment by dongido001** [comment]
To use it on the browser, use https://cdn.jsdelivr.net/npm/@dongido/vue-viaudio@0.2.8/dist/vue-viaudio.umd.js

I have included it on the doc [here](https://github.com/dongido001/vue-viaudio/blob/master/README.md#on-the-browser)

**Comment by mangowi** [comment]
Hi again,
Thank you for your quick response.

I've setup per instruction, and I have got the  :src as an array of video URLs from Youtube and MP4 files. But unfortunately, no video is being played.

I don't know what I am doing wrong.
Does "vue-viaudio" support only mp4, and not Youtube or Vimeo?

Here's my sandbox.

https://codesandbox.io/s/vue-viaudio-on-the-browser-xnt1s?fontsize=14

**Comment by dongido001** [comment]
Hi, 

It does not support Youtube, Vimeo, etc (other video streaming services). It only supports native video formats, mp3, mp4, etc.

If you want to play youtube videos, you check out https://github.com/surmon-china/vue-video-player, since this project only attempt to solve the reactive rendering of videos.
